[project]
name = "trading"
version = "0.1.0"
description = "trading position"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "httpx>=0.28.1",
    "pydantic>=2.13.4",
    "pytest>=9.1.1",
    "requests>=2.34.2",
    "uvicorn>=0.52.4",
]

[dependency-groups]
dev = [
    "pytest",
    "httpx",
]

[tool.setuptools]
packages = ["order_service", "position_service"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
